// Generated by CoffeeScript 1.7.1
var Template, TemplateFactory,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Template = require('./Template');

TemplateFactory = (function(_super) {
  __extends(TemplateFactory, _super);

  function TemplateFactory() {
    return TemplateFactory.__super__.constructor.apply(this, arguments);
  }

  TemplateFactory.prototype.templateRendererFactory = TemplateFactory.inject('templateRendererFactory');

  TemplateFactory.prototype.templateLoader = TemplateFactory.inject('templateLoader');

  TemplateFactory.prototype.createTemplate = function() {
    var template;
    template = new Template(this.templateRendererFactory.create());
    template.setLoader(this.templateLoader);
    return template;
  };

  return TemplateFactory;

})(Miwo.Object);

module.exports = TemplateFactory;
